name: saha-platform
services:
  - name: api
    source:
      type: git
      repository: https://github.com/MOPROGRAM/sahaplatform
      branch: main
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 5000
        public: true
        protocol: http
    environment:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: your_super_secret_saha_key_2025
      - key: DATABASE_URL
        value: ""  # Will be set by linked PostgreSQL service
    healthcheck:
      type: http
      path: /health
      port: 5000
      initial_delay: 30
      interval: 10
      timeout: 5
      failure_threshold: 3
    scaling:
      min: 1
      max: 10